// vue-app/src/components/SearchBar.vue
<template>
  <a-input-search
    class="pokemon-search"
    placeholder="Pikachu, Mewtwo or 5"
    enter-button
    @search="onSearch"
  />
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "SearchBar",
  props: {
    onSearch: {
      type: Function,
      required: true
    }
  }
});
</script>

<style scoped lang="scss">
.pokemon-search {
  margin-bottom: 24px;
}
</style>

// react-app/src/components/Search/SearchBar/SearchBar.tsx
import React, {FunctionComponent} from "react";
import {Input} from "antd";
import { SearchBarProps } from "./interfaces/SearchBarProps";
import styles from "./SearchBar.module.scss";

export const SearchBar: FunctionComponent<SearchBarProps> = (props) => {
    const {Search} = Input;

    return (
        <Search className={styles.pokemonSearch} placeholder="Pikachu, Mewtwo or 5" onSearch={props.onSearch} enterButton />
    )
}
