// react-app/src/components/Search/PokemonList/PokemonList.tsx
import React, { FunctionComponent } from "react";
import { PokemonListProps } from "./interfaces/PokemonListProps";
import { Avatar, Button, List } from "antd";
import { Pokemon } from "../../../interfaces/global/Pokemon";
import styles from "./PokemonList.module.scss";

export const PokemonList: FunctionComponent<PokemonListProps> = ({favouritePokemon, removeFavourite}) => {
    return (
        <List bordered
              size="large"
              dataSource={Array.from(favouritePokemon)}
              locale={{emptyText: 'Search for a Pokemon and add it to your list of favourites'}}
              header={<h3>My favourite Pokemon</h3>}
              renderItem={(item: Pokemon) => {
                  return (
                      <List.Item className={styles.listItem}>
                          <List.Item.Meta avatar={<Avatar size={96} src={item.sprites.front_default} />}
                                          title={item.name} />
                          <Button onClick={() => {
                              removeFavourite(item.id)
                          }} danger>Remove</Button>
                      </List.Item>
                  )
              }}>

        </List>
    )
}

// vue-app/src/components/PokemonList.vue
<template>
  <a-list
    :locale="{
      emptyText: 'Search for a Pokemon and add it to your list of favourites'
    }"
    :data-source="favouritePokemon"
  >
    <h3 slot="header">My favourite Pokemon</h3>
    <a-list-item size="large" bordered slot="renderItem" slot-scope="item">
      <a-list-item-meta>
        <a slot="title" class="pokemon-name">{{ item.name }}</a>
        <a-avatar :size="96" slot="avatar" :src="item.sprites.front_default" />
      </a-list-item-meta>
      <a-button type="danger" @click="onRemoveFavouritePokemon(item.id)"
        >Remove</a-button
      >
    </a-list-item>
  </a-list>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "PokemonList",
  props: ["favouritePokemon"],
  methods: {
    onRemoveFavouritePokemon(id: number) {
      this.$emit("remove-favourite", id);
    }
  }
});
</script>

<style scoped lang="scss">
.pokemon-name {
  text-transform: capitalize;
}
.ant-list-item-meta {
  align-items: center;
}
</style>
