// vue-app/src/components/Search.vue
<template>
  <div>
    <SearchBar :on-search="searchPokemonByIdOrName"></SearchBar>
    <div class="wrapper">
      <PokemonDetails
        :pokemon="currentPokemon"
        @add-to-favourites="onAddToFavourites"
      ></PokemonDetails>
      <PokemonList
        :favourite-pokemon="favouritePokemon"
        @remove-favourite="onRemoveFromFavourites"
      ></PokemonList>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { PokeService } from "@/services/PokeService";
import SearchBar from "@/components/SearchBar.vue";
import PokemonDetails from "@/components/PokemonDetails.vue";
import PokemonList from "@/components/PokemonList.vue";
import { Pokemon } from "@/interfaces/global/Pokemon";

export default Vue.extend({
  name: "Search",
  components: {
    SearchBar,
    PokemonDetails,
    PokemonList
  },
  data() {
    return {
      currentPokemon: null,
      favouritePokemon: []
    };
  },
  methods: {
    async searchPokemonByIdOrName(searchQuery: string | number) {
      let pokemon;
      try {
        pokemon = await PokeService.findPokemonByIdOrName(searchQuery);
      } catch (e) {
        this.$notification.error({
          message: "Pokemon doesn't exist",
          description: "A Pokemon by this ID or name does not exist."
        });
        return;
      }
      this.currentPokemon = pokemon;
    },
    onAddToFavourites(pokemon: Pokemon) {
      const pokemonSet: Set<Pokemon> = new Set(this.favouritePokemon);
      pokemonSet.add(pokemon);
      this.favouritePokemon = Array.from(pokemonSet);
    },
    onRemoveFromFavourites(id: number) {
      this.favouritePokemon = this.favouritePokemon.filter(
        (pokemon: Pokemon) => pokemon.id !== id
      );
    }
  }
});
</script>

<style scoped lang="scss">
.wrapper {
  display: flex;
  & > div {
    flex: 1 0 50%;
  }
}
</style>

// react-app/src/components/Search/Search.tsx
import React, { FunctionComponent, useCallback, useEffect, useState } from "react";
import axios from "axios";
import { SearchBar } from "./SearchBar/SearchBar";
import { notification } from "antd";
import { PokemonDetails } from "./PokemonDetails/PokemonDetails";
import { Pokemon } from "../../interfaces/global/Pokemon";
import { PokemonList } from "./PokemonList/PokemonList";
import styles from "./Search.module.scss";

export const Search: FunctionComponent = () => {
    const [query, setQuery] = useState("");
    const [currentPokemon, setCurrentPokemon] = useState(null);
    const [favouritePokemon, setFavouritePokemon] = useState(new Set<Pokemon>());
    const fetchPokemon = useCallback(async () => {
        let pokemon;
        try {
            pokemon = await axios(`https://pokeapi.co/api/v2/pokemon/${query}`);
        } catch (e) {
            notification.error({
                message: "Pokemon doesn't exist",
                description: "A Pokemon by this ID or name does not exist."
            });
            return;
        }

        setCurrentPokemon(pokemon.data);
    }, [query]);

    const searchPokemonByIdOrName = (idOrName: string) => {
        setQuery(idOrName);
    }

    const addToFavourites = (pokemon: Pokemon)  => {
        setFavouritePokemon(new Set<Pokemon>([...Array.from(favouritePokemon), pokemon]))
    }

    const removeFromFavourites = (id: number) => {
        const filteredFavouritePokemon = Array.from(favouritePokemon).filter((pokemon: Pokemon) => {
            return pokemon.id !== id;
        })
        setFavouritePokemon(new Set(filteredFavouritePokemon));
    }



    useEffect(() => {
        if (query !== "") {
            fetchPokemon();
        }
    }, [fetchPokemon, query]);

    return (
        <div>
            <SearchBar onSearch={searchPokemonByIdOrName} />
            <div className={styles.wrapper}>
                <PokemonDetails pokemon={currentPokemon} addFavouritePokemon={addToFavourites}/>
                <PokemonList favouritePokemon={favouritePokemon} removeFavourite={removeFromFavourites}/>
            </div>
        </div>
    )
}
